palette_config = {
    lines: {
        name: '接线与常用图形',
        items: [
            { name: '文字', image: '__text__', type: ht.Text },
            { name: '告警变色', image: 'symbols/palette-icon/basic/告警变色.json', type: ht.Node},
            { name: '数据绑定', image: 'symbols/palette-icon/basic/数据绑定.json', type: ht.Node},
            { name: '母线', image: 'symbols/palette-icon/lines/母线.json', type: ht.Node},
            { name: '坐标点', image: 'symbols/palette-icon/lines/坐标点.json', type: ht.Node},
            { name: '接合点', image: 'symbols/palette-icon/lines/接合点.json', type: ht.Node},
            { name: '交叉线路连接', image: 'symbols/palette-icon/lines/交叉线路连接.json', type: ht.Node},
            // { name: '圆形', image: 'symbols/palette-icon/basic/圆形.json', type: ht.Node},
            // { name: '矩形', image: 'symbols/palette-icon/basic/矩形.json', type: ht.Node},
            // { name: '圆角矩形', image: 'symbols/palette-icon/basic/圆角矩形.json', type: ht.Node},
            { name: '进度条', image: 'symbols/palette-icon/basic/进度条.json', type: ht.Node},
            { name: '刻度线', image: 'symbols/palette-icon/basic/刻度线.json', type: ht.Node},
        ]
    },
    // variable: {
    //     name: '测点配置组件',
    //     items: [
            // { name: '旋钮开关', image: 'symbols/palette-icon/others/旋钮开关.json', type: ht.Node},
            // { name: '旋钮开关-旋钮', image: 'symbols/palette-icon/others/旋钮开关-旋钮.json', type: ht.Node},
            // { name: '特殊开关', image: 'symbols/palette-icon/others/特殊开关.json', type: ht.Node},
        // ]
    // },
     power: {
        name: '电路相关',
        items: [
            { name: '开关', image: 'symbols/palette-icon/m-point/开关.json', type: ht.Node},
            { name: '断路器', image: 'symbols/palette-icon/m-point/断路器.json', type: ht.Node},
            { name: '断路器-详细', image: 'symbols/palette-icon/m-point/断路器-详细.json', type: ht.Node},
            { name: '断路器-FSL', image: 'symbols/palette-icon/m-point/断路器-FSL.json', type: ht.Node},
            { name: '手车', image: 'symbols/palette-icon/m-point/手车.json', type: ht.Node},
            { name: '刀闸', image: 'symbols/palette-icon/m-point/刀闸.json', type: ht.Node},
            { name: '接地开关', image: 'symbols/palette-icon/m-point/接地开关.json', type: ht.Node},

            { name: '负载', image: 'symbols/palette-icon/lines/负载.json', type: ht.Node},
            { name: '电抗', image: 'symbols/palette-icon/lines/电抗.json', type: ht.Node},
            { name: '放电间隙', image: 'symbols/palette-icon/lines/放电间隙.json', type: ht.Node},
            { name: '电缆', image: 'symbols/palette-icon/lines/电缆.json', type: ht.Node},
            { name: '避雷器', image: 'symbols/palette-icon/lines/避雷器.json', type: ht.Node},
            { name: '接地', image: 'symbols/palette-icon/lines/接地.json', type: ht.Node},
            { name: '箭头', image: 'symbols/palette-icon/lines/箭头.json', type: ht.Node},
            { name: '线圈', image: 'symbols/palette-icon/lines/线圈.json', type: ht.Node},
            { name: '消弧线圈', image: 'symbols/palette-icon/lines/弧圈.json', type: ht.Node},
            { name: '电阻', image: 'symbols/palette-icon/lines/电阻.json', type: ht.Node},
            { name: '电流互感器', image: 'symbols/palette-icon/lines/电流互感器.json', type: ht.Node},
            { name: '灭磁开关', image: 'symbols/palette-icon/lines/灭磁开关.json', type: ht.Node},
            { name: '接地负载', image: 'symbols/palette-icon/lines/接地负载.json', type: ht.Node},
            { name: '接地避雷器', image: 'symbols/palette-icon/lines/接地避雷器.json', type: ht.Node},
            { name: '接地放电间隙', image: 'symbols/palette-icon/lines/接地放电间隙.json', type: ht.Node},
            { name: '接地方块', image: 'symbols/palette-icon/lines/接地方块.json', type: ht.Node},
            { name: '接地电流互感器', image: 'symbols/palette-icon/lines/接地电流互感器.json', type: ht.Node},

            { name: '交流发电机', image: 'symbols/palette-icon/transformer/交流发电机.json', type: ht.Node},
            { name: '星型变压器', image: 'symbols/palette-icon/transformer/星型变压器.json', type: ht.Node},
            { name: '三角变压器', image: 'symbols/palette-icon/transformer/三角变压器.json', type: ht.Node},
            { name: '分接开关星型变压器', image: 'symbols/palette-icon/transformer/分接开关星型变压器.json', type: ht.Node},
            { name: '开口三角变压器', image: 'symbols/palette-icon/transformer/开口三角变压器.json', type: ht.Node},
            { name: '单绕组变压器', image: 'symbols/palette-icon/transformer/单绕组变压器.json', type: ht.Node},
            { name: '双绕组变压器', image: 'symbols/palette-icon/transformer/双绕组变压器.json', type: ht.Node},
            { name: '三绕组变压器', image: 'symbols/palette-icon/transformer/三绕组变压器.json', type: ht.Node},
            { name: '四绕组变压器', image: 'symbols/palette-icon/transformer/四绕组变压器.json', type: ht.Node},
            { name: '变压器常用接法', image: 'symbols/palette-icon/transformer/变压器常用接法.json', type: ht.Node},
            { name: '变压器常用接法2', image: 'symbols/palette-icon/transformer/变压器常用接法2.json', type: ht.Node},
            { name: '伊宁发变组主变', image: 'symbols/palette-icon/transformer/伊宁发变组主变.json', type: ht.Node},
            // { name: '主变', image: 'symbols/palette-icon/transformer/主变.json', type: ht.Node},
            // { name: '主变2', image: 'symbols/palette-icon/transformer/主变2.json', type: ht.Node},
            // { name: '主变3', image: 'symbols/palette-icon/transformer/主变3.json', type: ht.Node},
            // { name: '主变4', image: 'symbols/palette-icon/transformer/主变4.json', type: ht.Node},
            // { name: '主变5', image: 'symbols/palette-icon/transformer/主变5.json', type: ht.Node},
        ]
    },
    steam: {
        name: '火电相关',
        items: [
            { name: '状态标志', image: 'symbols/palette-icon/steam/状态标志.json', type: ht.Node},
            { name: '指示灯', image: 'symbols/palette-icon/steam/指示灯.json', type: ht.Node},
            { name: '泵-FSL', image: 'symbols/palette-icon/m-point/泵-FSL.json', type: ht.Node},
            { name: '泵-MATE', image: 'symbols/palette-icon/m-point/泵-MATE.json', type: ht.Node},
            { name: '电动阀', image: 'symbols/palette-icon/m-point/电动阀.json', type: ht.Node},
            { name: '气动阀', image: 'symbols/palette-icon/steam/气动阀.json', type: ht.Node},
            // { name: '止回阀', image: 'symbols/palette-icon/steam/止回阀.json', type: ht.Node},
            { name: '截止阀', image: 'symbols/palette-icon/steam/截止阀.json', type: ht.Node},
            { name: '三通阀', image: 'symbols/palette-icon/steam/三通阀.json', type: ht.Node},
            { name: '四通阀', image: 'symbols/palette-icon/steam/四通阀.json', type: ht.Node},
            { name: '球阀', image: 'symbols/palette-icon/steam/球阀.json', type: ht.Node},
            { name: '闸阀', image: 'symbols/palette-icon/steam/闸阀.json', type: ht.Node},
            { name: '止回阀', image: 'symbols/palette-icon/steam/止回阀.json', type: ht.Node},

            { name: '贮水槽', image: 'symbols/palette-icon/steam/贮水槽.json', type: ht.Node},
            { name: '水罐', image: 'symbols/palette-icon/steam/水罐.json', type: ht.Node},
            // { name: '压力缸-左', image: 'symbols/palette-icon/steam/压力缸-左.json', type: ht.Node},
            // { name: '压力缸-右', image: 'symbols/palette-icon/steam/压力缸-右.json', type: ht.Node},
            // { name: '压力缸管道', image: 'symbols/palette-icon/steam/压力缸管道.json', type: ht.Node},
            // { name: '低压蒸汽缸', image: 'symbols/palette-icon/steam/低压蒸汽缸.json', type: ht.Node},
            // { name: '冷凝水箱', image: 'symbols/palette-icon/steam/冷凝水箱.json', type: ht.Node},
            { name: '流向', image: 'symbols/palette-icon/steam/流向.json', type: ht.Node},
            { name: '压缩机', image: 'symbols/palette-icon/steam/压缩机.json', type: ht.Node},
            // { name: '辐射冷却剂', image: 'symbols/palette-icon/steam/辐射冷却剂.json', type: ht.Node},
            // { name: '低加', image: 'symbols/palette-icon/steam/低加.json', type: ht.Node},
            // { name: '疏水扩容器', image: 'symbols/palette-icon/steam/疏水扩容器.json', type: ht.Node},
            // { name: '过热器模板', image: 'symbols/palette-icon/steam/过热器模板.json', type: ht.Node},
            // { name: '除氧器', image: 'symbols/palette-icon/steam/除氧器.json', type: ht.Node},
            { name: '20', image: 'symbols/palette-icon/steam/20.json', type: ht.Node},
            { name: '21', image: 'symbols/palette-icon/steam/21.json', type: ht.Node},
            { name: '22', image: 'symbols/palette-icon/steam/22.json', type: ht.Node},
            { name: '23', image: 'symbols/palette-icon/steam/23.json', type: ht.Node},
            { name: '24', image: 'symbols/palette-icon/steam/24.json', type: ht.Node},
            { name: '电动机-带序号', image: 'symbols/palette-icon/steam/电动机-带序号.json', type: ht.Node},
        ]
    },
    // others: {
    //     name: '其他',
    //     items: [
    //         { name: '文本框-小', image: 'symbols/palette-icon/steam/文本框-小.json', type: ht.Node},
    //         { name: '文本框-中', image: 'symbols/palette-icon/steam/文本框-中.json', type: ht.Node},
    //         { name: '文本框-大', image: 'symbols/palette-icon/steam/文本框-大.json', type: ht.Node},
    //         { name: '按钮', image: 'symbols/palette-icon/steam/按钮.json', type: ht.Node},
    //         { name: '返回按键', image: 'symbols/palette-icon/steam/返回按键.json', type: ht.Node},
    //
    //     ]
    // },
};
