palette_config = {
    scene: {
        name: '电力',
        items: [
            { name: '文字', image: '__text__', type: ht.Text },
            { name: '坐标点', image: 'symbols/palette-icon/坐标点.json', type: ht.Node},
            { name: '开关', image: 'symbols/palette-icon/开关.json', type: ht.Node},
            { name: '旋钮开关', image: 'symbols/palette-icon/旋钮开关.json', type: ht.Node},
            { name: '圆上半', image: 'symbols/palette-icon/圆上半.json', type: ht.Node},
            { name: '圆下半', image: 'symbols/palette-icon/圆下半.json', type: ht.Node},
            { name: '放电间隙', image: 'symbols/palette-icon/放电间隙.json', type: ht.Node},
            { name: '避雷器', image: 'symbols/palette-icon/避雷器.json', type: ht.Node},
            { name: '红块', image: 'symbols/palette-icon/红块.json', type: ht.Node},
            { name: '接地', image: 'symbols/palette-icon/接地.json', type: ht.Node},
            { name: '三角', image: 'symbols/palette-icon/三角.json', type: ht.Node},
            { name: '箭头方块', image: 'symbols/palette-icon/箭头方块.json', type: ht.Node},
            { name: '侧长方形图标', image: 'symbols/palette-icon/侧长方形图标.json', type: ht.Node},
            { name: '附件01', image: 'symbols/palette-icon/附件01.json', type: ht.Node},
            { name: '附件02', image: 'symbols/palette-icon/附件02.json', type: ht.Node},
            { name: '附件03', image: 'symbols/palette-icon/附件03.json', type: ht.Node},
            { name: '附件04', image: 'symbols/palette-icon/附件04.json', type: ht.Node},
            { name: '附件05', image: 'symbols/palette-icon/附件05.json', type: ht.Node},
            // { name: '附件06', image: 'symbols/palette-icon/附件06.json', type: ht.Node},
            { name: '附件07', image: 'symbols/palette-icon/附件07.json', type: ht.Node},
            { name: '附件08', image: 'symbols/palette-icon/附件08.json', type: ht.Node},
            { name: '附件09', image: 'symbols/palette-icon/附件09.json', type: ht.Node},
            { name: '附件10', image: 'symbols/palette-icon/附件10.json', type: ht.Node},
            // { name: '附件11', image: 'symbols/palette-icon/附件11.json', type: ht.Node},
            { name: '附件12', image: 'symbols/palette-icon/附件12.json', type: ht.Node},
            { name: '附件13', image: 'symbols/palette-icon/附件13.json', type: ht.Node},
            { name: '附件14', image: 'symbols/palette-icon/附件14.json', type: ht.Node},
            { name: '附件15', image: 'symbols/palette-icon/附件15.json', type: ht.Node},
            { name: '附件16', image: 'symbols/palette-icon/附件16.json', type: ht.Node},
            { name: '附件17', image: 'symbols/palette-icon/附件17.json', type: ht.Node},
            { name: '附件18', image: 'symbols/palette-icon/附件18.json', type: ht.Node},
            { name: '附件19', image: 'symbols/palette-icon/附件19.json', type: ht.Node},
            { name: '附件20', image: 'symbols/palette-icon/附件20.json', type: ht.Node},
            { name: '附件21', image: 'symbols/palette-icon/附件21.json', type: ht.Node},
            // { name: '附件22', image: 'symbols/palette-icon/附件22.json', type: ht.Node},
            { name: '附件23', image: 'symbols/palette-icon/附件23.json', type: ht.Node},
            { name: '附件24', image: 'symbols/palette-icon/附件24.json', type: ht.Node},
            { name: '附件25', image: 'symbols/palette-icon/附件25.json', type: ht.Node},
            { name: '附件26', image: 'symbols/palette-icon/附件26.json', type: ht.Node},
            { name: '附件27', image: 'symbols/palette-icon/附件27.json', type: ht.Node},
            { name: '附件28', image: 'symbols/palette-icon/附件28.json', type: ht.Node},
            { name: '双箭头', image: 'symbols/palette-icon/双箭头.json', type: ht.Node},
            { name: '主变', image: 'symbols/palette-icon/主变.json', type: ht.Node},
            { name: '主变2', image: 'symbols/palette-icon/主变2.json', type: ht.Node},
            // { name: '几何图形', image: 'symbols/电力/rect.json', type: ht.Node},
            // { name: '箭头', image: 'symbols/电力/arrow.json', type: ht.Node},
            // { name: '地线', image: 'symbols/电力/earthwire.json', type: ht.Node},
            // { name: '绿灯', image: 'symbols/隧道用图标/交通灯/灯/灯-绿.json', type: ht.Node},
            // { name: 'T接线', image: 'symbols/电力/T接线.json', type: ht.Node},
            // { name: '避雷器', image: 'symbols/电力/避雷器.json', type: ht.Node},
            // { name: '带单触头高压跌落式熔断器的手车变压', image: 'symbols/电力/带单触头高压跌落式熔断器的手车变压.json', type: ht.Node},
            // { name: '带有载调压俩圈自耦变压器', image: 'symbols/电力/带有载调压俩圈自耦变压器.json', type: ht.Node},
            // { name: '刀闸', image: 'symbols/电力/刀闸.json', type: ht.Node},
            // { name: '电抗', image: 'symbols/电力/电抗.json', type: ht.Node},
            // { name: '电力电感器', image: 'symbols/电力/电力电感器.json', type: ht.Node},
            // { name: '电流互感器', image: 'symbols/电力/电流互感器.json', type: ht.Node},
            // { name: '电容式电压互感器', image: 'symbols/电力/电容式电压互感器.json', type: ht.Node},
            // { name: '电压互感器1', image: 'symbols/电力/电压互感器1.json', type: ht.Node},
            // { name: '电压互感器2', image: 'symbols/电力/电压互感器2.json', type: ht.Node},
            // { name: '电压互感器3', image: 'symbols/电力/电压互感器3.json', type: ht.Node},
            // { name: '电阻', image: 'symbols/电力/电阻.json', type: ht.Node},
            // { name: '放电间隙', image: 'symbols/电力/放电间隙.json', type: ht.Node},
            // { name: '分裂电抗', image: 'symbols/电力/分裂电抗.json', type: ht.Node},
            // { name: '高压熔断器', image: 'symbols/电力/高压熔断器.json', type: ht.Node},
            // { name: '接地', image: 'symbols/电力/接地.json', type: ht.Node},
            // { name: '禁止操作', image: 'symbols/电力/禁止操作.json', type: ht.Node},
            // { name: '禁止分闸', image: 'symbols/电力/禁止分闸.json', type: ht.Node},
            // { name: '禁止合闸', image: 'symbols/电力/禁止合闸.json', type: ht.Node},
            // { name: '禁止合闸线路有人工作', image: 'symbols/电力/禁止合闸线路有人工作.json', type: ht.Node},
            // { name: '禁止合闸有人工作', image: 'symbols/电力/禁止合闸有人工作.json', type: ht.Node},
            // { name: '静止无功补偿器', image: 'symbols/电力/静止无功补偿器.json', type: ht.Node},
            // { name: '开关', image: 'symbols/电力/开关.json', type: ht.Node},
            // { name: '其它遥测', image: 'symbols/电力/其它遥测.json', type: ht.Node},
            // { name: '熔断开关', image: 'symbols/电力/熔断开关.json', type: ht.Node},
            // { name: '设备在检修', image: 'symbols/电力/设备在检修.json', type: ht.Node},
            // { name: '手车刀闸', image: 'symbols/电力/手车刀闸.json', type: ht.Node},
            // { name: '停电', image: 'symbols/电力/停电.json', type: ht.Node},
            // { name: '无功遥测', image: 'symbols/电力/无功遥测.json', type: ht.Node},
            // { name: '消弧线圈', image: 'symbols/电力/消弧线圈.json', type: ht.Node},
            // { name: '已接地', image: 'symbols/电力/已接地.json', type: ht.Node},
            // { name: '有功遥测', image: 'symbols/电力/有功遥测.json', type: ht.Node},
            // { name: '闪烁灯', image: 'symbols/电力/light.json', type: ht.Node},
            // { name: '闪烁灯2', image: 'symbols/电力/xLight.json', type: ht.Node},
            // { name: '红灯', image: 'symbols/隧道用图标/交通灯/灯/灯-红.json', type: ht.Node},
            // { name: '在此工作', image: 'symbols/电力/在此工作.json', type: ht.Node},
            // { name: '站用变', image: 'symbols/电力/站用变.json', type: ht.Node},
            // { name: '阻波器', image: 'symbols/电力/阻波器.json', type: ht.Node},
        ]
    },
};



